// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikjbzoaprlzogzbxvkni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlramJ6b2Fwcmx6b2d6Ynh2a25pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjYxODEsImV4cCI6MjA3MTQ0MjE4MX0.2BIemmWb6_TBzPi5uwCur3ORSL9dMWwJnagOjsVAK3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});